name: build-app

on: [push]

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.14.0]
        os: [ubuntu-latest]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Setup Node env
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm v10.33.0 globally
        run: npm i -g pnpm@10.33.0

      - name: Install dependencies
        run: pnpm install

      - name: Build nextjs-app
        run: pnpm build